import random


class Message(object):
    def __init__(self, input_text):
        '''
        Initializes a Message object

        input_text (string): the message's text

        a Message object has one attribute:
            the message text
        '''
        self.input_text = input_text

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f"Message('{self.get_text()}')"

    def get_text(self):
        '''
        Used to access the message text outside of the class

        Returns: (string) the message text
        '''
        return self.input_text

    def shift_char(self, char, shift):
        '''
        Used to shift a character as described in the pset handout

        char (string): the single character to shift.
                    ASCII value in the range: 32<=ord(char)<=126
        shift (int): the amount to shift char by

        Returns: (string) the shifted character with ASCII value in the range [32, 126]
        '''
        # Convert char → ASCII number using ord
        ascii_val = ord(char)
        
        # Normalize into range 0–94 (ASCII 32–126 = 95 characters)
        normalized = ascii_val - 32
        
        # Add the shift
        shifted = normalized + shift
        
        # Use modulo (%) to wrap around
        wrapped = shifted % 95
        
        # Convert back to ASCII range
        new_ascii = wrapped + 32
        
        # Convert number → character using chr
        return chr(new_ascii)
    
    def apply_pad(self, pad):
        '''
        Used to calculate the ciphertext produced by applying a one time pad to the message text.
        For each character in the text at index i shift that character by
            the amount specified by pad[i]

        pad (list of ints): a list of integers used to encrypt the message text
                        len(pad) == len(the message text)

        Returns: (string) The ciphertext produced using the one time pad
        '''
        text = self.get_text()
        shifted_char = []
        
        # Raise Index Error if the lengths of pad and string are not equal
        if len(text) == len(pad):
            # Loop through characters by index
            for i in range(len(text)):
                
                # Get corresponding shift from pad
                shift = pad[i]
                
                # Call shift_char
                shifted = self.shift_char(text[i], shift)
                
                # Collect the shifted character
                shifted_char.append(shifted)
        else:
            raise ValueError("Lengths are not equal!")
            
        # Join all shifted characters into a string        
        return ''.join(shifted_char)


class PlaintextMessage(Message):
    def __init__(self, input_text, pad=None):
        super().__init__(input_text)
        '''
        Initializes a PlaintextMessage object.

        input_text (string): the message's text
        pad (list of ints OR None): the pad to encrypt the input_text or None if left empty
            if pad is not None then len(pad) == len(self.input_text)

        A PlaintextMessage object inherits from Message. It has three attributes:
            the message text
            the pad (list of integers, determined by pad
                or generated randomly using self.generate_pad() if pad is None)
            the ciphertext (string, input_text encrypted using the pad)
        '''
        # Check if the pad is empty then generate using the generate pad method
        if pad == None:
            pad = self.generate_pad()
          
        # Store a copy of pad
        self.pad = pad[:]

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f"PlaintextMessage('{self.get_text()}', '{self.get_pad()}')"

    def generate_pad(self):
        '''
        Generates a one time pad which can be used to encrypt the message text.

        The pad should be generated by making a new list and for each character
            in the message chosing a random number in the range [0, 110) and
            adding that number to the list.

        Returns: (list of integers) the new one time pad
        '''
        pad = []
        # Use the message text length to generate random values from 0 to 110
        for i in range(len(self.get_text())):
            pad.append(random.randint(0, 110))
            
        return pad

    def get_pad(self):
        '''
        Used to safely access your one time pad outside of the class

        Returns: (list of integers) a COPY of your pad
        '''
        return self.pad[:]

    def get_ciphertext(self):
        '''
        Used to access the ciphertext produced by applying pad to the message text

        Returns: (string) the ciphertext
        '''
        return self.apply_pad(self.pad)

    def change_pad(self, new_pad):
        '''
        Changes the pad used to encrypt the message text and updates any other
        attributes that are determined by the pad.

        new_pad (list of ints): the new one time pad that should be associated with this message.
            len(new_pad) == len(the message text)

        Returns: nothing
        '''
        # Stores independent copy
        self.pad = new_pad.copy()


class EncryptedMessage(Message):
    def __init__(self, input_text):
        '''
        Initializes an EncryptedMessage object

        input_text (string): the ciphertext of the message

        an EncryptedMessage object inherits from Message. It has one attribute:
            the message text (ciphertext)
        '''
        # Use the parent class attributes
        super().__init__(input_text)

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f"EncryptedMessage('{self.get_text()}')"

    def decrypt_message(self, pad):
        '''
        Decrypts the message text that was encrypted with pad as described in the writeup

        pad (list of ints): the new one time pad used to encrypt the message.
            len(pad) == len(the message text)

        Returns: (PlaintextMessage) the decrypted message (containing the pad)
        '''
        # Implement the negative values in the pad
        negated_pad = [-x for x in pad]
        
        # Use the apply method to perform the operations
        message = self.apply_pad(negated_pad)
        
        return PlaintextMessage(message, pad)
